name: Code style StyleLint CSS / SCSS

on:
   push:
      branches-ignore:
         - '**-dev'
   pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    name: StyleLint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions-hub/stylelint@master
        env:
          PATTERN: "src/**/*.scss"