name: Code style JavaScript

on:
   push:
      branches-ignore:
         - '**-dev'
   pull_request:

jobs:

  semistandard:
    runs-on: ubuntu-latest
    name: SemiStandard

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - run: npm install semistandard

      - name: Run semistandard
        run: npx semistandard